server:
  # port: 8080
  port: 8093

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
      # defaultZone: http://10.0.0.129:8080/eureka/

